import { describe, expect, test } from 'vitest';
import { applyDraftOverride, assertConsultantScope, materializeProfile, publicationBlockers, resolveException, reviewContextVersion, type ReviewDraftState } from './reviewWorkspace.js';
const context = reviewContextVersion({ report: 'sha', artifacts: ['a1'], goal: 'g1', cards: 'c1', updates: 'u1' });
const draft = (): ReviewDraftState => ({ version: 1, contextVersion: context, profile: { score: 700 }, overrides: [], exceptions: [{ key: 'conflict', blocking: true, status: 'OPEN', summary: 'Bureau conflict' }, { key: 'minor', blocking: false, status: 'OPEN', summary: 'Minor' }] });
describe('consultant review workspace', () => {
  test('keeps source immutable and records explicit override provenance', () => { const source={score:700}; const next=applyDraftOverride(draft(),{fieldPath:'score',originalValue:700,effectiveValue:720,reason:'Verified report',actorId:'consultant',sourceReference:{page:1},expectedVersion:1}); expect(source.score).toBe(700); expect(materializeProfile(source,next.overrides).score).toBe(720); expect(next.overrides[0]).toMatchObject({actorId:'consultant',reason:'Verified report'}); });
  test('blocking exception blocks until governed resolution while nonblocking may remain', () => { const current=draft(); expect(publicationBlockers(current,context)).toEqual(['EXCEPTION:conflict']); const resolved=resolveException(current,'conflict','Verified',1); expect(publicationBlockers(resolved,context)).toEqual([]); });
  test('stale context and concurrent edits fail visibly', () => { expect(publicationBlockers(draft(),'new')).toContain('STALE_REVIEW_CONTEXT'); expect(()=>applyDraftOverride(draft(),{fieldPath:'score',originalValue:700,effectiveValue:710,reason:'x',actorId:'c',sourceReference:{},expectedVersion:0})).toThrow('DRAFT_VERSION_CONFLICT'); });
  test('admin, insufficient capability and cross-client scope fail closed', () => { const base={capabilities:['review.publish'],scopedClientIds:['a'],clientId:'a'}; expect(()=>assertConsultantScope({...base,role:'ADMIN'})).toThrow('NOT_FOUND'); expect(()=>assertConsultantScope({...base,role:'CONSULTANT',clientId:'b'})).toThrow('NOT_FOUND'); });
});
