import { Alert, Button, Chip, CircularProgress, Divider, Stack, TextField, Typography } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { apiRequest } from '../auth/api';
import { PageHeader } from '../components/common/PageHeader';
import { SectionCard } from '../components/common/SectionCard';

type Candidate = { id: string; productId: string; disposition: string; role: string | null; clientSafeReason: string | null };
type StrategyView = { strategy: null | { id: string; roundId: string; status: string; version?: number; versions?: unknown[] }; current?: null | { id: string; version: number; status: string; aiProposal: Record<string, string[]> | null; candidates: Candidate[]; applications: Array<{ sequence: number; role: string; clientSafeReason: string }> }; approved: null | { version: number; approvedAt: string; cards: Array<{ productId: string; role: string; reason: string }>; sequence: Array<{ sequence: number; role: string; reason: string }> } };
type Product = { id: string; displayName: string; issuer: { name: string }; currentOfferVersion: null | { id: string; version: number; status: string }; currentInsightVersion: null | { id: string; clientSafeSummary: string } };

export function ClientStrategyPage() {
  const { roundId = '' } = useParams();
  const query = useQuery({ queryKey: ['client-strategy', roundId], queryFn: () => apiRequest<StrategyView>(`/api/v1/client/rounds/${roundId}/strategy`) });
  if (query.isLoading) return <CircularProgress />;
  if (query.isError || !query.data) return <Alert severity="error">Your strategy could not be loaded.</Alert>;
  if (!query.data.approved) return <Stack spacing={3}><PageHeader eyebrow="Current round" title="Your card strategy" description="Your consultant is preparing and reviewing your strategy." /><Alert severity="info">No strategy has been approved yet. Nothing is presented as a recommendation until consultant approval.</Alert></Stack>;
  return <Stack spacing={3}><PageHeader eyebrow="Approved strategy" title="Your card application plan" description="A clear sequence prepared and approved by your consultant." /><Alert severity="success">Strategy version {query.data.approved.version} is ready. Offer details should still be confirmed before any application.</Alert><SectionCard><Typography variant="h5">Your sequence</Typography><Stack divider={<Divider flexItem />} spacing={2}>{query.data.approved.sequence.map((item) => <Stack key={item.sequence} direction="row" spacing={2}><Chip label={item.sequence} /><Stack><Typography sx={{ fontWeight: 700 }}>{item.role}</Typography><Typography>{item.reason}</Typography></Stack></Stack>)}</Stack></SectionCard></Stack>;
}

export function ConsultantStrategyPage() {
  const { clientId = '', roundId = '' } = useParams();
  const qc = useQueryClient();
  const [search, setSearch] = useState('');
  const [approvalNote, setApprovalNote] = useState('Reviewed against the frozen client context and current governed offers.');
  const strategy = useQuery({ queryKey: ['strategy', clientId, roundId], queryFn: () => apiRequest<StrategyView>(`/api/v1/consultant/clients/${clientId}/rounds/${roundId}/strategy`) });
  const catalog = useQuery({ queryKey: ['strategy-catalog', clientId, search], queryFn: () => apiRequest<{ products: Product[] }>(`/api/v1/consultant/clients/${clientId}/strategy/catalog?search=${encodeURIComponent(search)}`) });
  const refresh = () => qc.invalidateQueries({ queryKey: ['strategy', clientId, roundId] });
  const draft = useMutation({ mutationFn: () => apiRequest(`/api/v1/consultant/clients/${clientId}/rounds/${roundId}/strategy/draft`, { method: 'POST', body: '{}' }), onSuccess: refresh });
  const candidate = useMutation({ mutationFn: ({ productId, disposition }: { productId: string; disposition: 'SHORTLISTED' | 'EXCLUDED' }) => apiRequest(`/api/v1/consultant/clients/${clientId}/strategies/${strategy.data!.strategy!.id}/candidates/${productId}`, { method: 'PUT', body: JSON.stringify({ expectedStrategyVersion: strategy.data!.strategy!.version, disposition, role: 'PLANNED', internalRationale: 'Selected after consultant comparison of governed product facts.', clientSafeReason: 'This product supports the goal and sequence reviewed with your consultant.' }) }), onSuccess: refresh });
  const shortlisted = useMemo(() => strategy.data?.current?.candidates.filter((item) => item.disposition === 'SHORTLISTED') ?? [], [strategy.data]);
  const sequence = useMutation({ mutationFn: () => apiRequest(`/api/v1/consultant/clients/${clientId}/strategies/${strategy.data!.strategy!.id}/sequence`, { method: 'PUT', body: JSON.stringify({ expectedStrategyVersion: strategy.data!.strategy!.version, items: shortlisted.map((item, index) => ({ candidateId: item.id, sequence: index + 1, role: item.role ?? 'PLANNED', timingRule: { instruction: index === 0 ? 'Apply only after final offer confirmation' : 'Wait for the prior outcome' }, dependencyRule: { priorSequenceComplete: index > 0 }, stopRule: { onApproved: 'pause-and-review', onDeclined: 'stop-and-review', onPending: 'wait', onSkipped: 'reconsider', onNotCompleted: 'reconsider', onUnexpected: 'stop-and-review' }, reconsiderationRule: { onApproved: 'review remaining need', onDeclined: 'consultant review', onPending: 'do not continue', onSkipped: 'resequence', onNotCompleted: 'resequence', onUnexpected: 'consultant review' }, internalRationale: 'Consultant-defined governed sequence.', clientSafeReason: item.clientSafeReason ?? 'This position protects the reviewed strategy sequence.' })) }) }), onSuccess: refresh });
  const approve = useMutation({ mutationFn: () => apiRequest(`/api/v1/consultant/clients/${clientId}/strategies/${strategy.data!.strategy!.id}/approve`, { method: 'POST', body: JSON.stringify({ expectedStrategyVersion: strategy.data!.strategy!.version, approvalNote, idempotencyKey: crypto.randomUUID() }) }), onSuccess: refresh });
  if (strategy.isLoading) return <CircularProgress />;
  return <Stack spacing={3}><PageHeader eyebrow="CRM strategy workspace" title="Build the client’s Round strategy" description="AI may organize evidence and propose possibilities. You select, sequence, validate, and approve." />{!strategy.data?.strategy ? <Button variant="contained" onClick={() => draft.mutate()}>Prepare strategy workspace</Button> : <><Alert severity="info">Source context is frozen for version {strategy.data.current?.version}. Refresh is required if material client data changes.</Alert><SectionCard><Typography variant="h5">AI brief</Typography><Typography>Proposal only — never a selection or approval.</Typography><pre>{JSON.stringify(strategy.data.current?.aiProposal, null, 2)}</pre></SectionCard><SectionCard><Typography variant="h5">Find and compare governed products</Typography><TextField label="Search issuer or product" value={search} onChange={(e) => setSearch(e.target.value)} /><Stack divider={<Divider flexItem />}>{catalog.data?.products.map((product) => <Stack key={product.id} direction={{ xs: 'column', md: 'row' }} spacing={2} sx={{ py: 2, justifyContent: 'space-between' }}><Stack><Typography sx={{ fontWeight: 700 }}>{product.issuer.name} · {product.displayName}</Typography><Typography>{product.currentInsightVersion?.clientSafeSummary ?? 'No approved insight summary'}</Typography><Typography variant="caption">Offer version {product.currentOfferVersion?.version ?? 'unavailable'}</Typography></Stack><Stack direction="row"><Button onClick={() => candidate.mutate({ productId: product.id, disposition: 'SHORTLISTED' })}>Shortlist</Button><Button onClick={() => candidate.mutate({ productId: product.id, disposition: 'EXCLUDED' })}>Exclude</Button></Stack></Stack>)}</Stack></SectionCard><SectionCard><Typography variant="h5">Sequence and approval</Typography><Typography>{shortlisted.length} shortlisted product(s)</Typography><Button disabled={!shortlisted.length || sequence.isPending} onClick={() => sequence.mutate()}>Validate proposed sequence</Button><TextField fullWidth multiline label="Approval note" value={approvalNote} onChange={(e) => setApprovalNote(e.target.value)} /><Button variant="contained" disabled={strategy.data.current?.status !== 'READY_FOR_APPROVAL' || approve.isPending} onClick={() => approve.mutate()}>Approve immutable strategy</Button></SectionCard></>}{(draft.error || candidate.error || sequence.error || approve.error) && <Alert severity="error">{(draft.error ?? candidate.error ?? sequence.error ?? approve.error)?.message}</Alert>}</Stack>;
}
